export const supabaseURL = "https://cvntqzbkycchmtwwfeuo.supabase.co";

export const anonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bnRxemJreWNjaG10d3dmZXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwOTU4NDQsImV4cCI6MjA1MTY3MTg0NH0.gD-YoB9kDIgo18tw6DqQNL9L8cDpZKT63ttGgDYcKyw";